
[functions.create-chanda]
enabled = true
verify_jwt = false
import_map = "./functions/create-chanda/deno.json"
entrypoint = "./functions/create-chanda/index.ts"

[functions.review-qr-chanda]
enabled = true
verify_jwt = false
import_map = "./functions/review-qr-chanda/deno.json"
entrypoint = "./functions/review-qr-chanda/index.ts"
